"""Deterministic rendering of a SpecPackage into OpenSpec files, with normalization
and a structural validator that gates every write."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field

from bokken.handoff.schema import CapabilityDraft, RequirementDraft, ScenarioDraft, SpecPackage


@dataclass
class Exclusion:
    statement: str
    assumption_id: str
    evidence_refs: list[str]


@dataclass
class ValidationItem:
    statement: str
    assumption_id: str
    reason: str  # "untested" | "requires_real_validation"


@dataclass
class HandoffContext:
    change_id: str
    session_name: str
    mode: str
    problem_statement: str
    concept: str
    assumption_ids: list[str]  # register order; indexes map into this
    contradicted_indexes: set[int]
    exclusions: list[Exclusion]
    validation_items: list[ValidationItem]
    trace_ids: dict[str, str | None]  # problem_statement/concept/recommendation -> event id
    dojo: bool = False
    extra: dict = field(default_factory=dict)


class HandoffFormatError(Exception):
    pass


def kebab(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    if not slug:
        raise HandoffFormatError(f"cannot derive a capability slug from {name!r}")
    return slug


def ensure_shall(statement: str) -> str:
    text = statement.strip().rstrip(".") + "."
    if "SHALL" in text:
        return text
    return "The system SHALL " + text[0].lower() + text[1:]


def scaffold_scenario(requirement: RequirementDraft) -> ScenarioDraft:
    return ScenarioDraft(
        name=f"{requirement.name} is satisfied",
        when=f"the behavior described by '{requirement.name}' is exercised",
        then="the outcome matches the requirement statement",
    )


def normalize(package: SpecPackage, ctx: HandoffContext) -> SpecPackage:
    """Drop anything resting on contradicted assumptions; repair format issues."""
    capabilities: list[CapabilityDraft] = []
    for capability in package.capabilities:
        requirements: list[RequirementDraft] = []
        for requirement in capability.requirements:
            if any(i in ctx.contradicted_indexes for i in requirement.assumption_indexes):
                continue  # contradicted in test: never becomes a requirement
            scenarios = requirement.scenarios or [scaffold_scenario(requirement)]
            requirements.append(
                RequirementDraft(
                    name=requirement.name.strip(),
                    statement=ensure_shall(requirement.statement),
                    scenarios=scenarios,
                    assumption_indexes=[
                        i
                        for i in requirement.assumption_indexes
                        if 0 <= i < len(ctx.assumption_ids)
                    ],
                )
            )
        if requirements:
            purpose = capability.purpose.strip()
            if len(purpose) < 50:
                purpose = (
                    f"{purpose} This capability serves the validated concept: {ctx.concept}."
                ).strip()
            capabilities.append(
                CapabilityDraft(
                    name=kebab(capability.name), purpose=purpose, requirements=requirements
                )
            )
    if not capabilities:
        raise HandoffFormatError(
            "no capability survived normalization; every requirement rested on "
            "contradicted assumptions"
        )
    return package.model_copy(update={"capabilities": capabilities})


def render_package(package: SpecPackage, ctx: HandoffContext) -> dict[str, str]:
    """Return {relative_path: content} for the whole handoff directory."""
    change_dir = f"openspec/changes/{ctx.change_id}"
    files: dict[str, str] = {}

    capability_lines = "\n".join(
        f"- `{c.name}`: {c.purpose.split('.')[0]}." for c in package.capabilities
    )
    what_changes = "\n".join(f"- {item}" for item in package.what_changes)
    files[f"{change_dir}/proposal.md"] = (
        f"# Proposal: {ctx.change_id}\n\n"
        f"## Why\n\n{package.why}\n\n"
        f"This proposal was generated by Bokken from the validated run "
        f"'{ctx.session_name}' (problem statement: {ctx.problem_statement}).\n\n"
        f"## What Changes\n\n{what_changes}\n\n"
        f"## Capabilities\n\n### New Capabilities\n\n{capability_lines}\n\n"
        f"### Modified Capabilities\n\n(none)\n\n"
        f"## Impact\n\nGreenfield MVP implementation of the validated concept: "
        f"{ctx.concept}.\n"
    )

    exclusions = (
        "\n".join(
            f"- Do NOT build on: {e.statement} — contradicted in test "
            f"(assumption `{e.assumption_id}`, evidence: "
            f"{', '.join(f'`{r}`' for r in e.evidence_refs) or 'see dossier'})"
            for e in ctx.exclusions
        )
        or "- none: no assumption was contradicted in test"
    )
    decisions = "\n".join(f"- {d}" for d in package.design_decisions) or "- none recorded"
    files[f"{change_dir}/design.md"] = (
        f"# Design: {ctx.change_id}\n\n"
        f"## Context\n\n{package.design_context or ctx.concept}\n\n"
        f"Derived from a Bokken run; full reasoning and evidence live in the run's "
        f"Session Dossier.\n\n"
        f"## Goals / Non-Goals\n\n**Goals:**\n\n- Implement the validated concept as "
        f"specified in this change's capability specs.\n\n**Non-Goals (exclusions from "
        f"the run's test results):**\n\n{exclusions}\n\n"
        f"## Decisions\n\n{decisions}\n\n"
        f"## Risks / Trade-offs\n\n- Items listed as validation tasks in tasks.md rest "
        f"on untested or simulated evidence and must be validated with real users.\n"
    )

    for capability in package.capabilities:
        body = [f"# {capability.name} - spec\n", "## Purpose\n", capability.purpose + "\n"]
        body.append("## ADDED Requirements\n")
        for requirement in capability.requirements:
            body.append(f"### Requirement: {requirement.name}\n")
            body.append(requirement.statement + "\n")
            for scenario in requirement.scenarios:
                body.append(f"#### Scenario: {scenario.name}\n")
                body.append(f"- **WHEN** {scenario.when}")
                body.append(f"- **THEN** {scenario.then}\n")
        files[f"{change_dir}/specs/{capability.name}/spec.md"] = "\n".join(body)

    groups = list(package.task_groups)
    task_lines: list[str] = [f"# Tasks: {ctx.change_id}\n"]
    n = 0
    for group in groups:
        n += 1
        task_lines.append(f"## {n}. {group.name}\n")
        for m, task in enumerate(group.tasks, start=1):
            verified = task if "verify" in task.lower() else f"{task}; verify with a test"
            task_lines.append(f"- [ ] {n}.{m} {verified}")
        task_lines.append("")
    if ctx.validation_items:
        n += 1
        task_lines.append(f"## {n}. Real-world validation (mandatory)\n")
        for m, item in enumerate(ctx.validation_items, start=1):
            task_lines.append(
                f"- [ ] {n}.{m} Validate with real users ({item.reason}): "
                f"{item.statement} (assumption `{item.assumption_id}`); verify with "
                f"real-user evidence, not simulation"
            )
        task_lines.append("")
    files[f"{change_dir}/tasks.md"] = "\n".join(task_lines)

    banner = ""
    if ctx.dojo:
        banner = (
            "\n> SIMULATED VALIDATION. This concept was validated against a governed "
            "synthetic persona panel, not real users. Complete the 'Real-world "
            "validation' tasks before treating flagged requirements as proven.\n"
        )
    files["README.md"] = (
        f"# Bokken handoff: {ctx.change_id}\n{banner}\n"
        f"Build-ready OpenSpec specifications for the validated concept of run "
        f"'{ctx.session_name}'.\n\n"
        "## Ingesting into a target repository\n\n"
        "1. Initialize OpenSpec in the target repo if needed: `openspec init`.\n"
        f"2. Copy `{change_dir}` into the target repo's `openspec/changes/`.\n"
        "3. Validate: `openspec validate --strict`.\n"
        "4. Implement with your coding harness (e.g. `/opsx:apply` in Claude Code), "
        "then archive.\n\n"
        "`traceability.json` maps every capability and requirement back to the "
        "originating Bokken ledger events; the run's `dossier/` holds the full "
        "evidence graph.\n"
    )

    trace = {
        "change_id": ctx.change_id,
        "session": ctx.session_name,
        "ledger_refs": ctx.trace_ids,
        "capabilities": {
            c.name: {
                r.name: {"assumption_ids": [ctx.assumption_ids[i] for i in r.assumption_indexes]}
                for r in c.requirements
            }
            for c in package.capabilities
        },
        "exclusions": [
            {"assumption_id": e.assumption_id, "statement": e.statement} for e in ctx.exclusions
        ],
    }
    files["traceability.json"] = json.dumps(trace, indent=2, sort_keys=True) + "\n"
    return files


_REQUIREMENT = re.compile(r"^### Requirement: .+", re.MULTILINE)
_SCENARIO = re.compile(r"^#### Scenario: .+", re.MULTILINE)


def validate_package(files: dict[str, str]) -> list[str]:
    """Structural OpenSpec-format checks. Returns a list of problems (empty = valid)."""
    problems: list[str] = []
    spec_files = {p: c for p, c in files.items() if "/specs/" in p and p.endswith("spec.md")}
    if not spec_files:
        problems.append("no capability spec files")
    for path, content in spec_files.items():
        capability = path.split("/specs/")[1].split("/")[0]
        if capability != kebab(capability):
            problems.append(f"{path}: capability directory is not kebab-case")
        if "## Purpose" not in content or "## ADDED Requirements" not in content:
            problems.append(f"{path}: missing Purpose or ADDED Requirements section")
        purpose = content.split("## Purpose", 1)[-1].split("##", 1)[0].strip()
        if len(purpose) < 50:
            problems.append(f"{path}: Purpose shorter than 50 characters")
        requirements = _REQUIREMENT.findall(content)
        if not requirements:
            problems.append(f"{path}: no requirements")
        for block in re.split(r"^### Requirement: ", content, flags=re.MULTILINE)[1:]:
            name = block.splitlines()[0]
            if "SHALL" not in block:
                problems.append(f"{path}: requirement {name!r} has no SHALL statement")
            if not _SCENARIO.search(block):
                problems.append(f"{path}: requirement {name!r} has no scenario")
            if "- **WHEN**" not in block or "- **THEN**" not in block:
                problems.append(f"{path}: requirement {name!r} scenario lacks WHEN/THEN")
    proposal = next((c for p, c in files.items() if p.endswith("proposal.md")), "")
    if "### New Capabilities" not in proposal:
        problems.append("proposal.md: missing New Capabilities section")
    tasks = next((c for p, c in files.items() if p.endswith("tasks.md")), "")
    if not re.search(r"^- \[ \] \d+\.\d+ ", tasks, re.MULTILINE):
        problems.append("tasks.md: no numbered checkbox tasks")
    return problems
