"""The panel: governed synthetic participants for the Dojo and synthetic-first research."""

from bokken.panel.casting import (
    OCEAN_TRAITS,
    ROLE_AGENTS,
    SAMPLING_AXES,
    CastingError,
    PanelKind,
    Persona,
    cast_panel,
    journal_manifest,
)
from bokken.panel.corpus import Citation, Corpus, Source
from bokken.panel.governance import (
    ContaminationError,
    ConvergenceBlockedError,
    CriteriaFrozenError,
    PanelConfigError,
    check_firewall,
    freeze_criteria,
    frozen_criteria,
    require_skeptic_challenge,
    requires_real_validation,
    skeptic_has_challenged,
    strip_preferences,
    validate_panel_config,
)
from bokken.panel.grounding import (
    Abstention,
    GroundedAnswer,
    Interviewer,
    PersonaTurnGenerator,
    ProfileOpinion,
    grounding_health,
)

__all__ = [
    "OCEAN_TRAITS",
    "ROLE_AGENTS",
    "SAMPLING_AXES",
    "Abstention",
    "CastingError",
    "Citation",
    "ContaminationError",
    "ConvergenceBlockedError",
    "Corpus",
    "CriteriaFrozenError",
    "GroundedAnswer",
    "Interviewer",
    "PanelConfigError",
    "PanelKind",
    "Persona",
    "PersonaTurnGenerator",
    "ProfileOpinion",
    "Source",
    "cast_panel",
    "check_firewall",
    "freeze_criteria",
    "frozen_criteria",
    "grounding_health",
    "journal_manifest",
    "require_skeptic_challenge",
    "requires_real_validation",
    "skeptic_has_challenged",
    "strip_preferences",
    "validate_panel_config",
]
